@startuml Basic Sample
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(trader, "Trader")
Person(traderPlus, "Trader+")
Person(admin, "Admin")

System_Boundary(c1, "") {
    Container(web_app, "Web Application", "Software system", "Allows traders to view trading indicators and approach them as strategies")
}

System(tinkoffAPI, "tinkoff API")

Rel(trader, web_app, "Views limited data visualization", "HTTP")
Rel(traderPlus, web_app, "Views all data visualization", "HTTP")
Rel(admin, web_app, "Manages users", "HTTP")

Rel(web_app, tinkoffAPI, "Gets market data from", "HTTPS")
@enduml
