@startuml Basic Sample
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(singlePage, "Single-page application", "Container: Java Script & React", "Provides market data visualization and user data management")
System_Boundary(c2, "") {
    Container(candleController, "Candle Controller", "Component: Spring Rest Controller", "")
    Container(strategyController, "Strategy Controller", "Component: Spring Rest Controller", "")

    Container(strategyComponent, "Strategy Factory Component", "Component: Spring Bean", "")
    Container(candleComponent, "Candle Component", "Component: Spring Bean", "")

    Container(candleRepository, "Candle Repository", "Component: Spring Repository", "")
}
Container(db, "DataBase", "Container: MySQL", "stores users and market candles")


Rel(singlePage, candleController, "Makes API calls to", "HTTP")
Rel(singlePage, strategyController, "Makes API calls to", "HTTP")

Rel(strategyController, strategyComponent, "Uses")
Rel(strategyController, candleComponent, "Uses")
Rel(candleController, candleComponent, "Uses")

Rel(strategyComponent, candleRepository, "Uses")
Rel(candleComponent, candleRepository, "Uses")

Rel(candleRepository, db, "Gets market data from", "HTTPS")
@enduml